# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ex_01_config = debug
  ex_02_config = debug
endif
ifeq ($(config),release)
  ex_01_config = release
  ex_02_config = release
endif

PROJECTS := ex_01 ex_02

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ex_01:
ifneq (,$(ex_01_config))
	@echo "==== Building ex_01 ($(ex_01_config)) ===="
	@${MAKE} --no-print-directory -C . -f ex_01.make config=$(ex_01_config)
endif

ex_02:
ifneq (,$(ex_02_config))
	@echo "==== Building ex_02 ($(ex_02_config)) ===="
	@${MAKE} --no-print-directory -C . -f ex_02.make config=$(ex_02_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ex_01.make clean
	@${MAKE} --no-print-directory -C . -f ex_02.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ex_01"
	@echo "   ex_02"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"