# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lua_tools_config = debug
  ex_01_config = debug
  ex_02_config = debug
  ex_03_config = debug
endif
ifeq ($(config),release)
  lua_tools_config = release
  ex_01_config = release
  ex_02_config = release
  ex_03_config = release
endif

PROJECTS := lua_tools ex_01 ex_02 ex_03

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lua_tools:
ifneq (,$(lua_tools_config))
	@echo "==== Building lua_tools ($(lua_tools_config)) ===="
	@${MAKE} --no-print-directory -C . -f lua_tools.make config=$(lua_tools_config)
endif

ex_01: lua_tools
ifneq (,$(ex_01_config))
	@echo "==== Building ex_01 ($(ex_01_config)) ===="
	@${MAKE} --no-print-directory -C . -f ex_01.make config=$(ex_01_config)
endif

ex_02: lua_tools
ifneq (,$(ex_02_config))
	@echo "==== Building ex_02 ($(ex_02_config)) ===="
	@${MAKE} --no-print-directory -C . -f ex_02.make config=$(ex_02_config)
endif

ex_03: lua_tools
ifneq (,$(ex_03_config))
	@echo "==== Building ex_03 ($(ex_03_config)) ===="
	@${MAKE} --no-print-directory -C . -f ex_03.make config=$(ex_03_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lua_tools.make clean
	@${MAKE} --no-print-directory -C . -f ex_01.make clean
	@${MAKE} --no-print-directory -C . -f ex_02.make clean
	@${MAKE} --no-print-directory -C . -f ex_03.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua_tools"
	@echo "   ex_01"
	@echo "   ex_02"
	@echo "   ex_03"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"